apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-postgres-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://your-helm-repo-url.git"
    targetRevision: main  # Or specific branch/tag
    path: "charts/vault-postgres-helm"  # Update with correct path if needed
    helm:
      values: |
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-postgres-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
