apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  database: {{ .Values.postgresql.database | b64enc }}
  username: {{ .Values.postgresql.user | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
