apiVersion: v1
kind: Pod
metadata:
  name: postgres-test-connection
  labels:
    app: postgres-test
spec:
  containers:
    - name: postgres-test
      image: postgres:15
      command: ["sh", "-c", "PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'"]
      env:
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.database }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.password }}"
  restartPolicy: Never
