apiVersion: v1
kind: Pod
metadata:
  name: postgres-test-connection
  labels:
    app: postgres-test
spec:
  containers:
    - name: postgres-test
      image: postgres:15
      command: ["sh", "-c", "PGPASSWORD={{ .Values.postgresql.password }} psql -h postgres -U {{ .Values.postgresql.user }} -d {{ .Values.postgresql.database }} -c 'SELECT 1'"]
  restartPolicy: Never
