{{- if .Values.vault.ingress.enabled | default false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vault-postgres-helm.fullname" . }}
  labels:
    {{- include "vault-postgres-helm.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.vault.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vault-postgres-helm.fullname" . }}
                port:
                  number: {{ .Values.vault.service.port }}
{{- end }}
